import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const port=4292,base=`http://127.0.0.1:${port}`,child=spawn(process.execPath,['server/server.mjs'],{cwd:new URL('..',import.meta.url).pathname,env:{...process.env,PORT:String(port)},stdio:'ignore'});
const wait=async()=>{for(let i=0;i<40;i++){try{if((await fetch(base+'/api/health')).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('server')};
const req=async(p,m='GET',b)=>{const r=await fetch(base+p,{method:m,headers:{'content-type':'application/json'},body:b?JSON.stringify(b):undefined});return {r,d:await r.json()}};
try{
  await wait();await req('/api/demo/reset','POST',{});let {d}=await req('/api/bootstrap?role=owner');const c=d.customers[0];
  await req(`/api/customers/${c.id}`,'PUT',{billingMethod:'Per Service',billingAnchor:'2026-08-01'});let out=await req('/api/jobs','POST',{customerId:c.id,propertyId:c.primaryPropertyId,service:'Standard Lawn Care',date:'2026-08-28',time:'1:00 PM',amount:77,status:'Scheduled'});const j=out.d.job;out=await req(`/api/jobs/${j.id}/status`,'POST',{status:'Completed',completedDate:'2026-08-28'});assert.equal(out.r.status,200);assert.ok(out.d.invoice);assert.equal(out.d.invoice.status,'Ready to Send');assert.equal(out.d.invoice.communicationStatus,'Ready to Send');
  out=await req(`/api/invoices/${out.d.invoice.id}/send`,'POST',{channel:'Email'});assert.equal(out.d.invoice.status,'Sent');
  const c2=d.customers[1];await req(`/api/customers/${c2.id}`,'PUT',{billingMethod:'Bi-Weekly',billingAnchor:'2026-08-01'});out=await req('/api/jobs','POST',{customerId:c2.id,propertyId:c2.primaryPropertyId,service:'Standard Lawn Care',date:'2026-08-02',time:'1:00 PM',amount:50,status:'Scheduled'});const bjob=out.d.job;out=await req(`/api/jobs/${bjob.id}/status`,'POST',{status:'Completed',completedDate:'2026-08-02'});assert.equal(out.d.invoice,null);out=await req('/api/billing/process','POST',{asOf:'2026-08-15'});assert.equal(out.d.created.length,1);assert.equal(out.d.created[0].billingMethod,'Bi-Weekly');assert.equal(out.d.created[0].status,'Ready to Send');
  const c3=d.customers[2];await req(`/api/customers/${c3.id}`,'PUT',{billingMethod:'Monthly',billingAnchor:'2026-08-28'});out=await req('/api/jobs','POST',{customerId:c3.id,propertyId:c3.primaryPropertyId,service:'Standard Lawn Care',date:'2026-08-10',time:'2:00 PM',amount:45,status:'Scheduled'});const m1=out.d.job;await req(`/api/jobs/${m1.id}/status`,'POST',{status:'Completed',completedDate:'2026-08-10'});out=await req('/api/jobs','POST',{customerId:c3.id,propertyId:c3.primaryPropertyId,service:'Standard Lawn Care',date:'2026-08-20',time:'2:00 PM',amount:45,status:'Scheduled'});const m2=out.d.job;await req(`/api/jobs/${m2.id}/status`,'POST',{status:'Completed',completedDate:'2026-08-20'});out=await req('/api/billing/process','POST',{asOf:'2026-08-27'});assert.equal(out.d.created.length,0);out=await req('/api/billing/process','POST',{asOf:'2026-08-28'});assert.equal(out.d.created.length,1);assert.equal(out.d.created[0].jobIds.length,2);assert.equal(out.d.created[0].amount,90);
  const c4=d.customers[3];await req(`/api/customers/${c4.id}`,'PUT',{billingMethod:'Manual'});out=await req('/api/jobs','POST',{customerId:c4.id,propertyId:c4.primaryPropertyId,service:'Standard Lawn Care',date:'2026-08-28',time:'3:00 PM',amount:60,status:'Scheduled'});const man=out.d.job;out=await req(`/api/jobs/${man.id}/status`,'POST',{status:'Completed',completedDate:'2026-08-28'});assert.equal(out.d.invoice,null);
  out=await req('/api/payroll','POST',{teamId:d.team[0].id,employee:d.team[0].name,hours:8,rate:d.team[0].rate,amount:192});assert.equal(out.r.status,201);out=await req('/api/maintenance','POST',{equipment:'Parity mower',model:'ZT',serial:'P-1',currentReading:'100 hr',type:'Oil / filter',due:'2026-09-01',vendor:'Shop',cost:75,status:'Upcoming'});assert.equal(out.r.status,201);
  out=await req('/api/bootstrap?role=owner');assert.ok(Array.isArray(out.d.billingQueue));assert.ok(out.d.customers[0].billingMethod);assert.ok(out.d.team[0].emergencyContact);assert.ok(out.d.payroll.length>=1);console.log('parity-upgrade: PASS')
}finally{child.kill('SIGTERM')}
