import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const root=new URL('..',import.meta.url);
const advanced=await readFile(new URL('app/modules/advanced.js',root),'utf8');
const app=await readFile(new URL('app/app.js',root),'utf8');
const provider=await readFile(new URL('app/modules/map-provider.js',root),'utf8');
const training=JSON.parse(await readFile(new URL('server/data/training-seed.json',root),'utf8'));
assert.match(advanced,/const allOpen=.*Completed.*Cancelled/);
assert.match(advanced,/const open=allOpen\.filter\(j=>j\.date===routeDateSelection\)/);
assert.match(advanced,/id="routeDateSelect"/);
assert.match(advanced,/future dates are never chained into today’s drive/);
assert.match(app,/todayJobs=allJobs\.filter\(j=>j\.date===todayISO\)/);
assert.match(app,/routeJobs=todayJobs\.filter/);
assert.match(app,/loadDashboardRouteMap\(routeJobs\)/);
assert.match(provider,/optimizedTrip\(points = \[\], origin = null, preference='fastest'\)/);
assert.match(provider,/routedPoints=hasOrigin\?\[origin,\.\.\.points\]:points/);
const open=training.jobs.filter(j=>!['Completed','Cancelled'].includes(j.status));
const dates=[...new Set(open.map(j=>j.date))];
assert.ok(dates.length>5,'training data should span multiple route dates');
assert.ok(open.length>Math.max(...dates.map(d=>open.filter(j=>j.date===d).length)),'all future jobs must not be one route');
console.log('routing-daily: PASS');
