import { coordinatesFor, installBaseLayers, roadRoute, optimizedTrip, geocodeFullAddress, externalRouteUrl } from './map-provider.js';
export function renderAdvanced(view,ctx){
  const {$, $$, data, esc, money, badge, hero, panel, setHeader, api, toast, load, modal, closeModal, field, textarea, select}=ctx;
  const alerts=buildAlerts(data);
  if(view==='fullworkspace'){
    setHeader('OPERATIONS','Paradise full workspace');
    const groups=[
      ['Customers & Sales','Customers, leads and quotes share one account/property record.','◎'],
      ['Scheduling & Routes','Jobs, route order, crew handoffs and weather readiness.','⌖'],
      ['Invoices & Payments','Printable invoices, balances and payment records.','$'],
      ['Communications','Preferred-contact customer messaging and communication history.','✉'],
      ['Equipment & Inventory','Maintenance, operating expenses and reorder alerts.','⚒'],
      ['History & Alerts','Audit history, warnings and owner priorities in one place.','!']
    ];
    $('#content').innerHTML=`<section class="workspace-dew-hero"><div><span class="eyebrow">PARADISE OPERATIONS</span><h2>We Make Your Lawn Paradise Perfect.</h2><p>The original Paradise Lawn Care functions now live inside the shared Business-in-a-Box navigation and data model. This workspace is a native overview — not a second program running inside the first.</p></div><img src="/app/assets/paradise-logo-original.png" alt="Paradise Lawn Care"></section><div class="workspace-native-grid">${groups.map((g,i)=>`<article class="workspace-module-card" data-target="${['customers','schedule','billing','communications','operations','history'][i]}"><i>${g[2]}</i><h3>${g[0]}</h3><p>${g[1]}</p><b>Open module →</b></article>`).join('')}</div><section class="panel parity-panel"><div class="panel-head"><div><span class="eyebrow">FUNCTION PARITY</span><h3>Original Paradise workspace incorporated</h3></div></div><div class="parity-chips"><span>Home / Dashboard</span><span>Invoices</span><span>Quotes</span><span>Scheduling</span><span>Customers</span><span>Communications</span><span>Employees / Team</span><span>Maintenance</span><span>Operating Expenses</span><span>Inventory</span><span>Weather</span><span>Photos / Attachments</span><span>History</span><span>Alerts</span></div></section>`;
    $$('.workspace-module-card').forEach(card=>card.onclick=()=>{const target=card.dataset.target;document.querySelector(`.nav-item[data-view="${target}"]`)?.click()});
    return true;
  }
  if(view==='alerts'){
    setHeader('COMMAND CENTER','Alerts & priorities');
    $('#content').innerHTML=hero('ALERTS','What needs attention','A unified priority view derived from receivables, customer requests, inventory, maintenance and schedule status.')+
      `<div class="priority-grid">${alerts.map(a=>`<article class="priority-card ${a.level}"><span>${esc(a.group)}</span><strong>${esc(a.title)}</strong><p>${esc(a.detail)}</p><b>${esc(a.action)}</b></article>`).join('')||'<div class="empty-state compact"><h2>No active priorities</h2></div>'}</div>`;
    return true;
  }
  if(view==='history'){
    setHeader('RECORDS','History');
    const types=[...new Set((data.activity||[]).map(a=>a.type||'system'))].sort();
    $('#content').innerHTML=hero('AUDIT LEDGER','Activity history','Search, filter and export the shared audit ledger for customers, quotes, jobs, invoices, payments, communications, maintenance and settings.',`<button class="btn secondary" id="exportHistory">Export CSV</button>`)+
      `<section class="panel"><div class="history-toolbar"><label class="field"><span>Search</span><input id="historySearch" type="search" placeholder="Customer, invoice, job, note…"></label><label class="field"><span>Category</span><select id="historyType"><option value="">All categories</option>${types.map(t=>`<option>${esc(t)}</option>`).join('')}</select></label></div><div class="history-list" id="historyList"></div></section>`;
    const draw=()=>{const q=($('#historySearch').value||'').toLowerCase(),t=$('#historyType').value;const rows=(data.activity||[]).filter(a=>(!t||(a.type||'system')===t)&&(!q||`${a.text} ${a.type} ${a.time}`.toLowerCase().includes(q)));$('#historyList').innerHTML=rows.map(a=>`<div><i></i><span><strong>${esc(a.text)}</strong><small>${esc(a.type||'system')} · ${esc(a.time)}</small></span></div>`).join('')||'<div class="empty-row">No matching activity</div>'};
    $('#historySearch').oninput=draw;$('#historyType').onchange=draw;draw();
    $('#exportHistory').onclick=()=>{const rows=[['Time','Type','Activity'],...(data.activity||[]).map(a=>[a.time||'',a.type||'system',a.text||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('\"','\"\"')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`paradise-history-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
    return true;
  }
  if(view==='weather'){
    setHeader('TREASURE COAST','Weather & radar');
    $('#content').innerHTML=hero('LIVE WEATHER','Treasure Coast weather center','Restored from the original Paradise application: National Weather Service conditions and forecast plus animated RainViewer radar over a Leaflet map.',`<button class="btn primary" id="refreshWeather">Refresh weather</button>`)+
      `<div class="metrics" id="weatherMetrics"><div class="metric"><span>STATUS</span><strong>Loading…</strong><small>Port St. Lucie reference point</small></div></div>`+
      `<div class="weather-workspace"><section class="panel weather-radar-panel"><div class="panel-head"><div><span class="eyebrow">LIVE RADAR</span><h3>Treasure Coast precipitation radar</h3></div><div class="row-actions"><button class="tiny action-green" id="radarPlay">▶ Play</button><button class="tiny action-orange" id="radarRefresh">Refresh radar</button></div></div><div id="weatherRadarMap" class="weather-radar-map"></div><div class="radar-status" id="radarStatus">Loading radar frames…</div></section><section><div class="forecast-grid" id="forecastGrid"></div></section></div>`+
      panel('Rain-aware operating notes','ROUTE PLANNING',`<div class="weather-notes"><div><b>Wet turf</b><p>Avoid rutting or tearing saturated lawns when conditions make mowing inappropriate.</p></div><div><b>Storm recovery</b><p>Route changes remain schedule decisions; weather information does not automatically cancel jobs.</p></div><div><b>Customer communication</b><p>Use Messages to prepare delay notices for affected customers.</p></div></div>`);
    let radarMap=null,radarLayers=[],radarFrames=[],radarIndex=0,radarTimer=null;
    const codeText=c=>({0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Drizzle',53:'Drizzle',55:'Drizzle',61:'Rain',63:'Rain',65:'Heavy rain',80:'Showers',81:'Showers',82:'Heavy showers',95:'Thunderstorms'}[c]||'Variable');
    const loadForecast=async()=>{const box=$('#weatherMetrics'),forecast=$('#forecastGrid');box.innerHTML='<div class="metric"><span>STATUS</span><strong>Loading…</strong><small>National Weather Service</small></div>';forecast.innerHTML='';try{const points=await fetch('https://api.weather.gov/points/27.2730,-80.3582',{headers:{Accept:'application/geo+json'}});if(!points.ok)throw new Error('NWS point lookup unavailable');const pd=await points.json();const [fr,stations]=await Promise.all([fetch(pd.properties.forecast),fetch(pd.properties.observationStations)]);const fj=await fr.json(),sj=await stations.json();let obs=null;if(sj.features?.[0]?.id){const or=await fetch(sj.features[0].id+'/observations/latest');if(or.ok)obs=(await or.json()).properties}const periods=fj.properties?.periods||[],tempC=obs?.temperature?.value,temp=tempC==null?(periods[0]?.temperature??'--'):Math.round(tempC*9/5+32),windKph=obs?.windSpeed?.value,wind=windKph==null?(periods[0]?.windSpeed||'--'):Math.round(windKph*0.621371)+' mph',rain=periods[0]?.probabilityOfPrecipitation?.value??0,condition=obs?.textDescription||periods[0]?.shortForecast||'Current conditions';box.innerHTML=`<div class="metric"><span>TEMPERATURE</span><strong>${temp}°F</strong><small>${esc(condition)}</small></div><div class="metric"><span>RAIN CHANCE</span><strong>${rain}%</strong><small>Next forecast period</small></div><div class="metric"><span>WIND</span><strong>${esc(wind)}</strong><small>${esc(periods[0]?.windDirection||'')}</small></div><div class="metric"><span>ALERT AREA</span><strong>Treasure Coast</strong><small>Port St. Lucie reference point</small></div>`;const paired=[];for(let i=0;i<periods.length&&paired.length<4;i++){const p=periods[i];if(!p.isDaytime)continue;let night=periods.slice(i+1).find(n=>!n.isDaytime);paired.push({day:p,night})}forecast.innerHTML=paired.map(({day,night})=>`<article class="forecast-day paired"><header><b>${esc(day.name.replace(/^This /,''))}</b><span>${esc(day.shortForecast)}</span></header><div class="forecast-halves"><div class="forecast-half day"><small>DAY</small><strong>${day.temperature}°${esc(day.temperatureUnit)}</strong><span>Rain ${day.probabilityOfPrecipitation?.value??0}%<br>${esc(day.windDirection)} ${esc(day.windSpeed)}</span></div><div class="forecast-half night"><small>NIGHT</small><strong>${night?`${night.temperature}°${esc(night.temperatureUnit)}`:'—'}</strong><span>${night?`${esc(night.shortForecast)} · Rain ${night.probabilityOfPrecipitation?.value??0}%`:'Forecast pending'}</span></div></div></article>`).join('')}catch(e){box.innerHTML=`<div class="metric"><span>CONNECTION</span><strong>Weather unavailable</strong><small>${esc(e.message)} · Check internet and press Refresh</small></div>`;forecast.innerHTML='<article class="forecast-day"><b>Offline</b><span>Live weather requires an internet connection.</span></article>'}};
    const showRadar=i=>{if(!radarFrames.length||!radarMap)return;radarLayers.forEach((l,n)=>l.setOpacity(n===i ? .72 : 0));radarIndex=i;const frame=radarFrames[i];$('#radarStatus').textContent=frame?`Radar frame: ${new Date(frame.time*1000).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`:'Radar ready'};
    const loadRadar=async()=>{const L=window.L,status=$('#radarStatus');if(!L){status.textContent='Leaflet radar library unavailable.';return}if(!radarMap){radarMap=L.map('weatherRadarMap',{zoomControl:true}).setView([27.20,-80.25],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(radarMap);L.rectangle([[26.98,-80.45],[27.42,-80.05]],{color:'#23b943',weight:2,fill:false,dashArray:'6 6'}).addTo(radarMap).bindTooltip('Paradise service region')}try{status.textContent='Loading RainViewer radar…';const r=await fetch('https://api.rainviewer.com/public/weather-maps.json',{cache:'no-store'});if(!r.ok)throw new Error('RainViewer unavailable');const j=await r.json();radarFrames=(j.radar?.past||[]).slice(-8);radarLayers.forEach(l=>radarMap.removeLayer(l));radarLayers=radarFrames.map(f=>L.tileLayer(`${j.host}${f.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:0,zIndex:500,maxNativeZoom:7,maxZoom:18,attribution:'Radar by RainViewer'}).addTo(radarMap));showRadar(Math.max(0,radarFrames.length-1));setTimeout(()=>radarMap.invalidateSize(),100)}catch(e){status.textContent='Radar unavailable: '+e.message}};
    $('#refreshWeather').onclick=()=>{loadForecast();loadRadar()};$('#radarRefresh').onclick=loadRadar;$('#radarPlay').onclick=()=>{const b=$('#radarPlay');if(radarTimer){clearInterval(radarTimer);radarTimer=null;b.textContent='▶ Play';return}b.textContent='❚❚ Pause';radarTimer=setInterval(()=>showRadar((radarIndex+1)%Math.max(1,radarFrames.length)),700)};loadForecast();loadRadar();return true;
  }
  if(view==='routes'){
    setHeader('FIELD OPERATIONS','Route center');
    const open=(data.jobs||[]).filter(j=>!['Completed','Cancelled'].includes(j.status)).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||'')));
    const miles=Number(data.metrics?.routeMiles||0);
    const customers=data.customers||[];
    const enriched=open.map((j,i)=>{const c=customers.find(x=>x.id===j.customerId);const prop=c?.properties?.find(x=>x.id===j.propertyId);return {...j,fullAddress:prop?.address||c?.property||j.address,_index:i}});
    $('#content').innerHTML=hero('ROUTE CENTER','Scheduled-job route','The map follows real roads when the routing service is available. Satellite / Hybrid is the default view. Scheduled jobs define the route; “Use My Location” only changes the driving origin.',`<button class="btn primary" id="openMaps">Open Route in Google Maps</button>`)+
      `<div class="metrics"><div class="metric"><span>OPEN STOPS</span><strong>${open.length}</strong><small>Scheduled/open jobs</small></div><div class="metric"><span>REFERENCE MILES</span><strong id="routeMilesMetric">${miles.toFixed(1)}</strong><small>Road route when available</small></div><div class="metric"><span>EST. SERVICE TIME</span><strong>${Math.round(open.reduce((sum,j)=>sum+Number(j.duration||0),0)/6)/10} hr</strong><small>Before drive time</small></div><div class="metric"><span>ROUTE REVENUE</span><strong>${money(open.reduce((sum,j)=>sum+Number(j.amount||0),0))}</strong><small>Internal operational value</small></div></div>`+
      `<section class="route-map-shell"><div class="route-map-help"><div><strong>Interactive road route</strong><span>Satellite / Hybrid is the default layer. Exact customer/property coordinates are used when available; unresolved demo addresses use clearly approximate area positions.</span></div><div class="row-actions"><button class="tiny action-green" id="routeFit">Fit Stops</button><button class="tiny action-orange" id="routeOrigin">Use My Location as Origin</button><button class="tiny action-green" id="routeRecommend">Recommend Efficient Order</button></div></div><div id="routeLeafletMap" class="route-map-frame" role="application" aria-label="Interactive road route map"></div><div class="route-origin-status" id="routeOriginStatus">Loading road route…</div><div class="route-recommendation" id="routeRecommendation"><b>Route recommendation</b><span>Analyze the road network for an efficient stop order. Recommendations never change the schedule automatically.</span></div></section>`+
      panel('Scheduled route stops','JOB DETAILS',`<div class="route-stop-list detailed">${open.map((j,i)=>`<div class="route-stop-row" data-stop="${i}"><b>${i+1}</b><span><strong>${esc(j.date||'')} · ${esc(j.time||'')} · ${esc(j.customer)}</strong><small>${esc(enriched[i].fullAddress||j.address||'No address')}<br>${esc(j.service||'Service')} · Crew: ${esc(j.crew||'Unassigned')} · ${money(j.amount||0)}</small></span>${badge(j.status)}</div>`).join('')||'<div class="empty-row">No open route stops</div>'}</div>`);
    const L=window.L;let map=null,markers=[],origin=null,routeLine=null,recommendLine=null,pts=enriched.map((j,i)=>coordinatesFor(j,i)),fitPoints=pts;
    const drawRoad=async(points)=>{if(!map||points.length<2)return;try{const route=await roadRoute(points);routeLine&&map.removeLayer(routeLine);routeLine=L.polyline(route.geometry,{color:'#8dff3d',weight:6,opacity:.92}).addTo(map);fitPoints=route.geometry;map.fitBounds(L.latLngBounds(route.geometry).pad(.10));$('#routeMilesMetric').textContent=(route.distanceMeters/1609.344).toFixed(1);$('#routeOriginStatus').textContent=`Road route loaded · ${(route.distanceMeters/1609.344).toFixed(1)} mi · about ${Math.round(route.durationSeconds/60)} min driving before service time.`}catch(e){routeLine&&map.removeLayer(routeLine);routeLine=L.polyline(points,{color:'#ff8618',weight:3,opacity:.75,dashArray:'8 8'}).addTo(map);fitPoints=points;$('#routeOriginStatus').textContent='Road routing provider unavailable. Dashed line is a temporary stop-order fallback.'}};
    if(L&&$('#routeLeafletMap')){map=L.map('routeLeafletMap',{zoomControl:true,scrollWheelZoom:true}).setView([27.20,-80.25],10);installBaseLayers(map,L,'satellite');markers=pts.map((c,i)=>L.marker(c).addTo(map).bindPopup(`<strong>${i+1}. ${esc(open[i].customer)}</strong><br>${esc(open[i].date||'')} ${esc(open[i].time||'')}<br>${esc(open[i].service)}<br>${esc(enriched[i].fullAddress||open[i].address)}`));if(pts.length)map.fitBounds(L.latLngBounds(pts).pad(.18));setTimeout(()=>map.invalidateSize(),120);drawRoad(pts)}else{$('#routeLeafletMap').innerHTML='<div class="map-fallback"><strong>Map library unavailable</strong><span>The scheduled stop list below remains fully usable.</span></div>'}
    $$('.route-stop-row').forEach(row=>row.onclick=()=>{const i=Number(row.dataset.stop);markers[i]?.openPopup();if(map&&pts[i])map.flyTo(pts[i],16)});
    $('#routeFit').onclick=()=>{if(map&&fitPoints.length)map.fitBounds(L.latLngBounds(origin?[origin,...fitPoints]:fitPoints).pad(.10))};
    $('#routeOrigin').onclick=()=>{const status=$('#routeOriginStatus');if(!navigator.geolocation){status.textContent='Browser location is unavailable. Route remains based on scheduled jobs.';return}status.textContent='Requesting your current location…';navigator.geolocation.getCurrentPosition(async pos=>{origin=[pos.coords.latitude,pos.coords.longitude];L.circleMarker(origin,{radius:9,color:'#ff7a00',fillColor:'#ffb21b',fillOpacity:1,weight:3}).addTo(map).bindPopup('Current device location').openPopup();await drawRoad([origin,...pts]);status.textContent='Origin set to current device location. Scheduled job order is unchanged unless you choose a recommendation.'},()=>status.textContent='Location permission was not granted. Origin remains the first scheduled stop.')};
    $('#routeRecommend').onclick=async()=>{const box=$('#routeRecommendation');if(pts.length<2){box.innerHTML='<b>Route recommendation</b><span>Add at least two open stops to analyze.</span>';return}box.innerHTML='<b>Route recommendation</b><span>Analyzing road travel efficiency…</span>';try{const trip=await optimizedTrip(pts);recommendLine&&map.removeLayer(recommendLine);recommendLine=L.polyline(trip.geometry,{color:'#ff8a18',weight:5,opacity:.92,dashArray:'10 6'}).addTo(map);const names=trip.order.map((idx,n)=>`${n+1}. ${esc(open[idx]?.customer||'Stop')}`);box.innerHTML=`<b>Recommended road-efficient order</b><span>${names.join(' → ')}</span><small>${(trip.distanceMeters/1609.344).toFixed(1)} mi · about ${Math.round(trip.durationSeconds/60)} min drive time. This is a recommendation only; appointment/service windows and crew commitments remain the owner’s decision.</small>`;map.fitBounds(L.latLngBounds(trip.geometry).pad(.10))}catch(e){box.innerHTML=`<b>Route recommendation unavailable</b><span>${esc(e.message)}. Current scheduled order remains unchanged.</span>`}};
    $('#openMaps').onclick=()=>{const url=externalRouteUrl(enriched,origin?`${origin[0]},${origin[1]}`:'');if(!url)return toast('No scheduled addresses are available');window.open(url,'_blank','noopener')};
    return true;
  }
  if(view==='photos'){
    setHeader('FIELD RECORDS','Photos & attachments');
    const customers=data.customers||[], jobs=data.jobs||[], atts=data.attachments||[];
    $('#content').innerHTML=hero('PHOTO RECORDS','Before, after, property & damage photos','Images are tenant-scoped and linked to a customer/property/job. Local prototype storage keeps image data in the JSON adapter; production uses object storage.')+
      `<div class="grid two"><section class="panel"><div class="panel-head"><div><span class="eyebrow">ADD PHOTO</span><h3>Attach field image</h3></div></div><form id="photoForm" class="form-grid">${select('Customer','customerId',[{value:'',label:'Select customer'},...customers.map(c=>({value:c.id,label:`${c.accountNumber} · ${c.name}`}))],'')}${select('Job','jobId',[{value:'',label:'Optional job'},...jobs.map(j=>({value:j.id,label:`${j.id} · ${j.customer}`}))],'')}${select('Category','category',['Before','After','Property','Damage'],'Before')}${field('Caption','caption','')}${field('Image','photo','','file','accept="image/*" required')}<div class="form-span"><button class="btn primary">Save photo</button><small class="help">Local build limit: approximately 5 MB per image.</small></div></form></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">ATTACHMENT LIBRARY</span><h3>${atts.length} saved image${atts.length===1?'':'s'}</h3></div></div><div class="photo-grid">${atts.map(a=>{const c=customers.find(x=>x.id===a.customerId);return `<figure class="photo-card"><img src="${esc(a.dataUrl)}" alt="${esc(a.caption||a.name)}"><figcaption><strong>${esc(a.category)} · ${esc(c?.name||'Unassigned')}</strong><span>${esc(a.caption||a.name)} · ${esc(a.created)}</span><button type="button" class="tiny photo-delete" data-id="${esc(a.id)}">Remove</button></figcaption></figure>`}).join('')||'<div class="empty-state compact"><h2>No photos attached yet</h2><p>Add a before, after, property or damage photo.</p></div>'}</div></section></div>`;
    $('#photoForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const file=f.photo.files[0];if(!file)return toast('Choose an image');if(file.size>5_000_000)return toast('Image is too large');const reader=new FileReader();reader.onload=async()=>{const customer=customers.find(c=>c.id===f.customerId.value);const propertyId=customer?.primaryPropertyId||'';await api('/api/attachments',{method:'POST',body:JSON.stringify({customerId:f.customerId.value,propertyId,jobId:f.jobId.value,category:f.category.value,caption:f.caption.value,name:file.name,dataUrl:reader.result})});toast('Photo saved');load('photos')};reader.readAsDataURL(file)};
    $$('.photo-delete').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this photo?'))return;await api(`/api/attachments/${encodeURIComponent(b.dataset.id)}`,{method:'DELETE'});toast('Photo removed');load('photos')});return true;
  }
  if(view==='documents'){
    setHeader('DOCUMENTS','Invoices & printable records');
    $('#content').innerHTML=hero('DOCUMENT CENTER','Printable invoice previews','The record remains API-backed; the print view is a presentation of the same invoice/customer/job identifiers.')+
      panel('Invoice documents','PRINT / PDF',`<div class="data-table"><div class="data-head"><span>Invoice</span><span>Customer</span><span>Amount</span><span>Status</span><span>Action</span></div>${(data.invoices||[]).map(i=>`<div class="data-row"><span><strong>${esc(i.id)}</strong><small>${esc(i.accountNumber||'')}</small></span><span>${esc(i.customer)}</span><span>${money(i.amount)}</span><span>${badge(i.status)}</span><span><button class="tiny doc-preview" data-id="${esc(i.id)}">Preview</button></span></div>`).join('')}</div>`);
    $$('.doc-preview').forEach(b=>b.onclick=()=>previewInvoice(b.dataset.id,ctx));return true;
  }
  if(view==='backup'){
    setHeader('ADMINISTRATION','Backup & portability');
    $('#content').innerHTML=hero('DATA SAFETY','Export or restore a complete tenant backup','Validated backup/restore keeps the Business-in-a-Box tenant portable without changing the Paradise presentation.',`<button class="btn primary" id="exportBackup">Export complete backup</button>`)+
      panel('Backup & restore','TENANT DATA',`<div class="settings-copy backup-studio"><p>Branding, customers, properties, quotes, jobs, invoices, communications, inventory, maintenance, attachments and activity remain tenant-scoped. Restore validates the file before replacing the current workspace.</p><label class="field"><span>Choose Business in a Box JSON backup</span><input id="restoreFile" type="file" accept="application/json,.json"></label><div class="row-actions"><button class="btn secondary" id="restoreBackup">Restore validated backup</button><button class="btn secondary" id="resetDemoAdvanced">Reset demo seed</button></div></div>`);
    $('#exportBackup').onclick=async()=>{const backup=await api('/api/backup/export');const blob=new Blob([JSON.stringify(backup.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(data.tenant?.shortName||'tenant').replace(/\W+/g,'-')}-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Complete backup exported')};
    $('#restoreBackup').onclick=()=>{const file=$('#restoreFile').files?.[0];if(!file)return toast('Choose a JSON backup first');const reader=new FileReader();reader.onload=async()=>{try{const payload=JSON.parse(reader.result);await api('/api/backup/restore',{method:'POST',body:JSON.stringify(payload)});toast('Backup restored');load('backup')}catch(error){toast(error.message||'Backup could not be restored')}};reader.readAsText(file)};
    $('#resetDemoAdvanced').onclick=async()=>{if(confirm('Reset the prototype to its packaged demo data?')){await api('/api/demo/reset',{method:'POST',body:'{}'});toast('Demo reset');load('backup')}};return true;
  }
  return false;
}

function buildAlerts(data){const a=[];const overdue=(data.invoices||[]).filter(i=>i.status!=='Paid'&&i.status!=='Void'&&i.due&&i.due<new Date().toISOString().slice(0,10));if(overdue.length)a.push({level:'red',group:'Billing',title:`${overdue.length} overdue invoice${overdue.length===1?'':'s'}`,detail:'Receivables are past their due date.',action:'Review Billing'});const low=(data.inventory||[]).filter(i=>Number(i.qty)<=Number(i.reorderAt));if(low.length)a.push({level:'yellow',group:'Inventory',title:`${low.length} item${low.length===1?'':'s'} at reorder level`,detail:low.map(i=>i.name).join(', '),action:'Review Operations'});const maint=(data.maintenance||[]).filter(m=>m.status!=='Completed'&&m.due&&m.due<=new Date().toISOString().slice(0,10));if(maint.length)a.push({level:'yellow',group:'Maintenance',title:`${maint.length} maintenance item${maint.length===1?'':'s'} due`,detail:maint.map(m=>m.equipment).join(', '),action:'Review Maintenance'});const req=(data.customerRequests||[]).filter(r=>r.status==='Open');if(req.length)a.push({level:'green',group:'Customers',title:`${req.length} open customer request${req.length===1?'':'s'}`,detail:'Portal requests are waiting for office review.',action:'Review Requests'});const ready=(data.invoices||[]).filter(i=>i.status==='Ready to Send'||i.communicationStatus==='Ready to Send');if(ready.length)a.push({level:'red',group:'Billing',title:`${ready.length} invoice${ready.length===1?' is':'s are'} ready to send`,detail:'Invoices are populated and waiting for owner review/manual send.',action:'Review Billing'});const unbilled=(data.billingQueue||[]).filter(g=>g.period?.ready);if(unbilled.length)a.push({level:'yellow',group:'Billing',title:`${unbilled.length} billing batch${unbilled.length===1?' is':'es are'} ready`,detail:'Completed services are ready to populate into invoices.',action:'Process Billing'});return a}

function previewInvoice(id,ctx){const {$,data,esc,money,modal}=ctx;const i=(data.invoices||[]).find(x=>x.id===id);if(!i)return;const c=(data.customers||[]).find(x=>x.id===i.customerId);const p=c?.properties?.find(x=>x.id===i.propertyId)||c?.properties?.[0];modal(`Invoice ${esc(i.id)}`,`<div class="invoice-paper" id="invoicePaper"><div class="invoice-brand"><img src="${esc(data.tenant?.brand?.appLogoUrl||'/app/assets/paradise-logo-original.png')}"><div><b>${esc(data.tenant?.name)}</b><span>${esc(data.tenant?.phone||'')}</span></div></div><div class="invoice-title"><h2>INVOICE</h2><span>${esc(i.id)} · ${esc(i.status)}</span></div><div class="invoice-cols"><div><small>BILL TO</small><b>${esc(c?.name||i.customer)}</b><span>${esc(c?.email||'')}</span><span>${esc(c?.phone||'')}</span></div><div><small>SERVICE LOCATION</small><b>${esc(p?.label||'Primary Property')}</b><span>${esc(p?.address||'')}</span><span>Account ${esc(i.accountNumber||'')}</span></div></div><div class="invoice-lines">${(i.lines||[]).map(l=>`<div><span>${esc(l.description)}</span><b>${money(l.amount??l.rate)}</b></div>`).join('')}</div><div class="invoice-total"><span>Total</span><strong>${money(i.amount)}</strong></div><p>Preferred contact: ${esc(c?.preferredContact||'Not specified')}</p></div><div class="modal-foot"><button class="btn primary" id="printInvoice">Print / Save PDF</button></div>`);$('#printInvoice').onclick=()=>window.print()}
